name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Main metrics with detailed plugins
      - name: Generate main metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaelvalen
          template: classic
          base: header, activity, community, repositories, metadata
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: Europe/Istanbul
          config_display: large
          config_padding: 0, 8 + 11%
          
          # Languages plugin
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: bytes-size, percentage
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          
          # Habits plugin - coding habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          
          # Activity plugin
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_timestamps: yes
          
          # Topics plugin
          plugin_topics: yes
          plugin_topics_mode: starred
          plugin_topics_limit: 15
          
          # Output
          filename: github-metrics.svg
          output_action: commit
          committer_branch: metrics
          committer_message: "Update main metrics"
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
      # Compact language statistics
      - name: Generate compact languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaelvalen
          template: classic
          base: ""
          config_timezone: Europe/Istanbul
          
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_categories: markup, programming
          
          filename: github-metrics-languages.svg
          output_action: commit
          committer_branch: metrics
          committer_message: "Update language metrics"
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
      # Isocalendar (contributions calendar)
      - name: Generate isocalendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaelvalen
          template: classic
          base: ""
          config_timezone: Europe/Istanbul
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          filename: github-metrics-calendar.svg
          output_action: commit
          committer_branch: metrics
          committer_message: "Update calendar metrics"
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
      # Activity details
      - name: Generate activity details
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: kaelvalen
          template: classic
          base: ""
          config_timezone: Europe/Istanbul
          
          plugin_followup: yes
          plugin_followup_sections: repositories
          
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 14
          
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          
          filename: github-metrics-activity.svg
          output_action: commit
          committer_branch: metrics
          committer_message: "Update activity metrics"
          committer_token: ${{ secrets.GITHUB_TOKEN }}
